name: Print file contents

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  print:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Check changes in dir_a
        id: check_dir_a
        shell: bash
        run: |
          diff_a=$( git diff --name-only HEAD^ HEAD -- dir_a )
          if [ ${#diff_a} -gt 1 ]; then has_a=true; else has_a=false; fi
          echo "has_changes=$has_a" >> $GITHUB_OUTPUT
          echo $diff_a
          echo $has_a

      - name: Check changes in dir_b
        id: check_dir_b
        run: |
          diff_b=$( git diff --name-only HEAD^ HEAD -- dir_b )
          if [ ${#diff_b} -gt 1 ]; then has_b=true; else has_b=false; fi
          echo "has_changes=$has_b" >> $GITHUB_OUTPUT
          echo $diff_b
          echo $has_b

      - name: Print contents in dir_a
        if: steps.check_dir_a.outputs.has_changes == 'true'
        shell: bash
        run: |
          echo 'Contents of dir_a/list_a.txt'
          cat dir_a/list_a.txt

      - name: Print contents in dir_b
        if: steps.check_dir_b.outputs.has_changes == 'true'
        shell: bash
        run: |
          echo 'Contents of dir_b/list_b.txt'
          cat dir_b/list_b.txt
